
auth.token=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

defaults.org=petch-development
defaults.project=boxoal-native

defaults.url=https://sentry.io/
